### ISSUE TITLE
Add node collection from Overpass

### ISSUE THREAD

**Issue by braktar** [VROOM-Project/vroom-frontend#49]
To ease the handling of the frontend, it may be useful to a way to generate simple instances directly from a small description. similarly to the following script: https://github.com/VROOM-Project/vroom-scripts/blob/master/src/overpass_to_json.py

It requires to have at least one point defined as depot.
Then: 
- [x] Add two new fields : key and value (corresponding to overpass tags, with a default value ex: amenity:pharmacy)
- [x] Add a link to openstreetmap wiki
- [x] Perform a request to Overpass API within the current bounding box
- removed: Reverse geocode the obtained nodes
- [x] Get node name from Overpass
- [x] Add the obtained nodes to the current node list

**Comment by jcoupey** [comment]
This would be a great way for users to easily design relevant problems without any programming/formatting skills, especially in the light of [the current situation](https://twitter.com/VroomProject/status/1245643065231982592).

I'd be happy to take part in the associated dev and push this to http://map.vroom-project.org/ as soon as it's available.

**Comment by jcoupey** [comment]
Couple notes on the technical side:

1. I'm not sure we'd really need a reverse geocoding step. Currently a click on the map triggers one because it's a way to use the address as a job description. But Overpass results would most of the time yield a `name` tag that would be even more relevant.

2. There is a limit on the total number of jobs that can be added through the frontend that reflects the limitation on the demo server. We'd have to deal with that, either by limiting the number of results retrieved from Overpass to the number of remaining jobs, or by checking against the total number of jobs upon additions.

**Comment by jcoupey** [comment]
This landed with #50 and is now live at http://map.vroom-project.org/
